name: Cypress Tests
on:
  workflow_dispatch:
jobs:
  cypress-tests:
    name: Chrome Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
